name: d4lf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pywin32
  - pip
  - pkg-config
  - pip:
    - Pillow
    - beautifultable
    - black
    - colorama
    - coverage
    - cryptography
    - dependencies/tesserocr-2.6.0-cp311-cp311-win_amd64.whl
    - keyboard
    - mouse
    - mss
    - numpy
    - opencv-python==4.8.1.78
    - natsort
    - parse
    - pre-commit
    - psutil
    - pyinstaller
    - pytesseract==0.3.10
    - pytest
    - pytest-env
    - pytest-mock
    - pytest-pythonpath
    - pytweening
    - rapidfuzz
    - tk
    - typing_extensions
