# Find all affix keys in "config/affixes.json". Resource of possible affixes: https://d4builds.gg/database/gear-affixes/

# Format is: [KEY, THRESHOLD, CONDITON]
# CONDITON can be "larger" or "smaller" and defaults to "larger"

# itemType must be any of:
#   helm, armor, pants, gloves, boots, ring, amulet, axe, tow-handed axe,
#   sword, two-handed sword, mace, two-handed mace, scythe, two-handed scythe,
#   bow, bracers, crossbow, dagger, polarm, shield, stff, wand, offhand, totem


Filters:
  - Helm:
      itemType: helm
      minPower: 725
      affixPool:
        - [basic_skill_attack_speed, 6]
        - [cooldown_reduction, 5]
        - [dexterity, 36]
        - [maximum_life, 580]
        - [total_armor, 9]
        - [ranks_of_poison_imbuement, 3]
        - [ranks_of_shadow_imbuement, 3]
      minAffixCount: 3

  - Armor:
      itemType: [armor, pants]
      minPower: 725
      affixPool:
        - [damage_reduction_from_close_enemies, 10]
        - [damage_reduction_from_distant_enemies, 12]
        - [damage_reduction, 5]
        - [total_armor, 9]
        - [maximum_life, 700]
        - [dodge_chance_against_close_enemies, 6.5]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 725
      affixPool:
        - [dexterity, 10]
        - [damage_reduction_from_distant_enemies, 12]
        - [damage_reduction, 5]
        - [total_armor, 9]
        - [maximum_life, 700]
      minAffixCount: 3

  # Example take all boots and rings
  - TakeAll:
      itemType: [boots]
      minPower: 0
      affixPool:
      minAffixCount: 0
