name: CI

on: [pull_request]

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: ruff format
        shell: powershell
        run: ruff format --check

      - name: ruff lint
        shell: powershell
        run: ruff check

      - name: Pytest
        shell: powershell
        run: pytest . -m "not selenium" -v -n logical
#      - name: Pytest selenium
#        shell: powershell
#        run: pytest . -m "selenium" -v
