name: CI

on: [ pull_request ]

concurrency:
  group: '${{github.workflow}}-${{github.ref}}'
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: ruff format
        shell: powershell
        run: ruff format --check

      - name: ruff lint
        shell: powershell
        run: ruff check

      - name: Pytest non web
        shell: powershell
        run: pytest . -m "not webtest" -v

      # for some reason, these take forever on ci. need to investigate. for now, disable
      # - name: Pytest web
      #   shell: powershell
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     pytest . -m "webtest" -v -n auto
      #   continue-on-error: true
      #   timeout-minutes: 10
