name: D4LF - CI
on: [ pull_request ]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: d4lf
          python-version: '3.12'
          use-mamba: true

      - name: Update environment
        run: mamba env update -n d4lf -f environment.yml

      - name: Conda info
        shell: powershell
        run: |
          conda info
          conda list

      - name: ruff lint
        uses: chartboost/ruff-action@v1

      - name: ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

      - name: Pytest non web
        shell: powershell
        run: |
          python -c "import sys; print(sys.version)"
          pytest . -m "not webtest" -v

      # for some reason, these take forever on ci. need to investigate. for now, disable
      # - name: Pytest web
      #   shell: powershell
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     pytest . -m "webtest" -v -n auto
      #   continue-on-error: true
      #   timeout-minutes: 10
