name: CI

on: [pull_request]

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        shell: powershell
        run: pre-commit run -a

      - name: Pytest
        shell: powershell
        run: pytest . -m "not selenium" -v -n logical
#      - name: Pytest selenium
#        shell: powershell
#        run: pytest . -m "selenium" -v
