name: D4LF - CI
on: [ pull_request ]
env:
  # To force cache update
  CACHE_NUMBER: 1
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: d4lf
          python-version: '3.12'
          use-mamba: true

      - name: Cache Conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run:
          mamba env update -n d4lf -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Conda info
        shell: powershell
        run: |
          conda info
          conda list

      - name: ruff lint
        uses: chartboost/ruff-action@v1

      - name: ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

      - name: Pytest
        shell: powershell
        run: |
          C:\Miniconda\condabin\conda.bat activate d4lf
          python -c "import sys; print(sys.version)"
          pytest . -m "not webtest" -v
          pytest . -m "webtest" -v -n auto
