name: CI

on: [ pull_request ]

concurrency:
  group: '${{github.workflow}}-${{github.ref}}'
  cancel-in-progress: true

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: ruff format
        shell: powershell
        run: ruff format --check

      - name: ruff lint
        shell: powershell
        run: ruff check

      - name: Pytest non web
        shell: powershell
        run: pytest . -m "not webtest" -v

      - name: Pytest requests
        shell: powershell
        run: pytest . -m "requests" -v -n auto

# for some reason it doesn't like selenium. skip for now
#      - name: Pytest selenium
#        shell: powershell
#        run: pytest . -m "requests" -v -n auto
#        continue-on-error: true
#        timeout-minutes: 10
