name: CI
on: [ pull_request ]
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Setup env
        uses: ./.github/actions/setup_env

      - name: ruff lint
        uses: chartboost/ruff-action@v1

      - name: ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

      - name: Pytest non web
        shell: powershell
        run: |
          python -c "import sys; print(sys.version)"
          pytest . -m "not webtest" -v

      # for some reason, these take forever on ci. need to investigate. for now, disable
      # - name: Pytest web
      #   shell: powershell
      #   run: |
      #     python -c "import sys; print(sys.version)"
      #     pytest . -m "webtest" -v -n auto
      #   continue-on-error: true
      #   timeout-minutes: 10
