name: Test

on:
  push:
    branches:
      - test-gh-action

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Send message to Discord
        run: |
          $webhookUrl = "${{ secrets.DISCORD_WEBHOOK_URL }}"
          $payload = @{
              username = "GitHub Actions"
              content = "Test <https://github.com/aeon0/d4lf>"
              allowed_mentions = @{
                parse = @()
              }
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $webhookUrl -Method Post -ContentType "application/json" -Body $payload
        shell: powershell
